from datetime import datetime
import csv
import json

if(__name__!='__main__'):
  from ..models import Enrollment, Student, Course, db

IGNORE_COLUMNS=['Gender','Address_1','Address_2','BirthDay',""]

# Function to extract data from an input file and save in a list of dictionaries
def text_to_dictionary_list(input_file):
  subject_list=[]
  with open(input_file,'r', newline='') as subjects:
    subject_reader=csv.DictReader(subjects,delimiter="\t")
    for subject in subject_reader:
      # remove personal information
      anonymized_subject={key:val for key, val in subject.items() if key not in IGNORE_COLUMNS}
      subject_list.append(anonymized_subject)
  return subject_list

# Function to insert a record into the student table
def insert_student(name, student_id):
  record=Student(name, student_id,dataset=datetime.now())
  db.session.add(record)
  db.session.commit()

# Function to insert a record into the course table
def insert_course(id,sect,c_title,ch):
  record=Course(course_id=id, section=sect, title=c_title, credit_hours=ch,dataset=datetime.now())
  db.session.add(record)
  db.session.commit()

# Function to insert a record into the enrollment table
def insert_enrollment(id,s_id,sect,gr):
  record=Enrollment(course_id=id, student_id=s_id, section=sect, grade=gr, dataset=datetime.now())
  db.session.add(record)
  db.session.commit()

# Helper method to print dictionary generated by Text_to_dictionary_list
def pretty_print(input_file):
  list_of_dictionaries=text_to_dictionary_list(input_file)
  print(json.dumps(list_of_dictionaries,sort_keys=True,indent=4))

# Function to upload all 3 data files

# def upload_all_files():
#   upload_course_data()
#   upload_transfer_data()
#   upload_person_data()

# # Function to extract and upload course_data.txt to database
# def upload_course_data():

# # Function to extract and upload person_data.txt to database
# def upload_person_data():

# # Function to extract and upload transfer_data.txt to database
# def upload_transfer_data():